/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StationsStationIdImport } from './routes/stations/$stationId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StationsStationIdRoute = StationsStationIdImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stations/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stations/$stationId'
  id: '__root__' | '/' | '/stations/$stationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StationsStationIdRoute: StationsStationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/stations/$stationId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/stations/$stationId": {
      "filePath": "stations/$stationId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
